package dto

import "admin/pkg/pagination"

// CreateUserRequest 创建用户请求
type CreateUserRequest struct {
	UserName string `json:"username" binding:"required"`          // 用户名
	Nickname string `json:"nickname" binding:"omitempty"`         // 昵称/显示名称
	Password string `json:"password" binding:"required"`          // 密码
	Phone    string `json:"phone" binding:"omitempty"`            // 手机号
	Email    string `json:"email" binding:"omitempty"`            // 邮箱
	Remark   string `json:"remark" binding:"omitempty"`           // 备注信息
	Status   int    `json:"status" binding:"omitempty,oneof=1 2"` // 状态 1:正常 2:禁用
	TenantID string `json:"tenant_id"`                            // 租户ID（可选，从上下文获取）
}

// UpdateUserRequest 更新用户请求
type UpdateUserRequest struct {
	Password string `json:"password" binding:"omitempty"`         // 密码
	Phone    string `json:"phone" binding:"omitempty"`            // 手机号
	Email    string `json:"email" binding:"omitempty"`            // 邮箱
	Status   int    `json:"status" binding:"omitempty,oneof=1 2"` // 状态 1:正常 2:禁用
	Nickname string `json:"nickname" binding:"omitempty"`         // 昵称/显示名称
	Remark   string `json:"remark" binding:"omitempty"`           // 备注信息
}

// UserInfo 用户基础信息（可复用）
type UserInfo struct {
	UserID        string `json:"user_id"`         // 用户ID
	UserName      string `json:"username"`        // 用户名
	Nickname      string `json:"nickname"`        // 昵称/显示名称
	Avatar        string `json:"avatar"`          // 头像URL
	Phone         string `json:"phone"`           // 手机号
	Email         string `json:"email"`           // 邮箱
	Status        int    `json:"status"`          // 状态 1:正常 2:禁用
	TenantID      string `json:"tenant_id"`       // 租户ID
	LastLoginTime int64  `json:"last_login_time"` // 最后登录时间
	CreatedAt     int64  `json:"created_at"`      // 创建时间
	UpdatedAt     int64  `json:"updated_at"`      // 更新时间
}

// UserResponse 用户响应
type UserResponse struct {
	User *UserInfo `json:"user"` // 用户基础信息
}

// ListUsersRequest 用户列表请求
type ListUsersRequest struct {
	pagination.Request  `json:",inline"`
	UserName            string `form:"username" binding:"omitempty"`         // 用户名模糊搜索
	Status              int    `form:"status" binding:"omitempty,oneof=1 2"` // 状态筛选
	TenantID            string `form:"tenant_id" binding:"omitempty"`        // 租户ID筛选
}

// ListUsersResponse 用户列表响应
type ListUsersResponse struct {
	pagination.Response `json:",inline"`
	List                []*UserResponse `json:"list"` // 列表数据
}

// ProfileResponse 用户档案响应（含角色和租户信息）
type ProfileResponse struct {
	User   *UserInfo   `json:"user"`   // 当前用户信息
	Tenant *TenantInfo `json:"tenant"` // 当前租户信息
	Roles  []*RoleInfo `json:"roles"`  // 用户角色列表
}

// AssignRolesRequest 为用户分配角色请求
type AssignRolesRequest struct {
	RoleCodes []string `json:"role_codes" binding:"required,min=1"` // 角色编码列表
}

// UserRolesResponse 用户角色响应
type UserRolesResponse struct {
	UserID   string      `json:"user_id"`   // 用户ID
	UserName string      `json:"username"`  // 用户名
	Roles    []*RoleInfo `json:"roles"`     // 角色列表
}

// ChangePasswordRequest 用户修改密码请求
type ChangePasswordRequest struct {
	OldPassword string `json:"old_password" binding:"required"` // 原密码
	NewPassword string `json:"new_password" binding:"required,min=6"` // 新密码
}

// ChangePasswordResponse 修改密码响应
type ChangePasswordResponse struct {
	Success bool   `json:"success"` // 是否成功
	Message string `json:"message"` // 提示信息
}

// ResetPasswordRequest 超管重置密码请求
type ResetPasswordRequest struct {
	Password string `json:"password" binding:"omitempty,min=6"` // 新密码，为空则自动生成
}

// ResetPasswordResponse 重置密码响应（密码只显示一次）
type ResetPasswordResponse struct {
	Password      string `json:"password,omitempty"` // 重置后的密码（仅重置时显示一次）
	AutoGenerated bool   `json:"auto_generated"`    // 是否自动生成
	Message       string `json:"message"`           // 提示信息
}
